# 项目相关配置
icoolkj:
  # 名称
  name: icoolKjOpenApi
  # 版本
  version: 1.0.2
server:
  # 端口
  port: 18080
spring:
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 16379
    # 数据库索引
    database: 1
    # 密码
    password: redis@2023
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/icoolkj-open-api?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: icoolkj
    password: icoolkj@@2023Test

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.icoolkj.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    com.icoolkj: debug
    org.springframework: warn

# 生成主键的规则标识
# 部署到不同tomcat下的id.worker都不能重复
sequence:
  # 机器标识ID【可用0、1、2、3、....31这32个数字】
  id-worker: 0
  # 数据中心ID【可用0、1、2、3、....31这32个数字】
  id-datacenter: 0

api:
  wrap:
    legalTime: 300
    secret: icoolkj
